name: CI

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v5

      - name: Install packaging deps
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends build-essential gcc-aarch64-linux-gnu gcc-arm-linux-gnueabihf
          sudo apt-get install -y --no-install-recommends python3-cryptography python3-minimal python3-pyelftools
          sudo apt-get install -y --no-install-recommends bc bison flex libgnutls28-dev libssl-dev python3-dev python3-jsonschema python3-setuptools python3-yaml swig uuid-dev yamllint

      - name: Set Variables UBOOT and TI_FIRMWARE
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          TAG="${GITHUB_REF##*/}"
          # 1. Extract TI_FIRMWARE (Everything after the LAST hyphen)
          TI_FIRMWARE="${TAG##*-}"
          # 2. Remove TI_FIRMWARE from the tag to get "UBOOT-TFA"
          REMAINDER="${TAG%-*}"
          # 3. Extract TFA (Everything after the LAST hyphen in the remainder)
          TFA="${REMAINDER##*-}"
          # 4. Extract UBOOT (Everything before the last hyphen in the remainder)
          UBOOT="${REMAINDER%-*}"
          echo "UBOOT=$UBOOT" >> $GITHUB_ENV
          echo "TFA=$TFA" >> $GITHUB_ENV
          echo "TI_FIRMWARE=$TI_FIRMWARE" >> $GITHUB_ENV

      - name: Build U-Boot
        run: ./build_u-boot.sh

      - name: Create tarball
        run: tar -cJf "public/bootfs.tar.xz" -C public tiboot3.bin tispl.bin u-boot.img

      - name: Generate os_list.json
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          ./tools/gen-os-list.py "${GITHUB_REF##*/}"
            
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: |
            public/tiboot3.bin
            public/tispl.bin
            public/u-boot.img
            public/bootfs.tar.xz
            public/os_list.json
